# Generated by Django 5.2.7 on 2025-10-05 19:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электрондук почта')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Колдонуучу аты')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='Аты')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Фамилиясы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активдүү')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Персонал')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Суперколдонуучу')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Кошулган датасы')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Акыркы кирүү')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Колдонуучу',
                'verbose_name_plural': 'Колдонуучулар',
                'ordering': ['-date_joined'],
            },
        ),
    ]
